### ISSUE TITLE
Can't execute add private from cheatsheet

### ISSUE THREAD

**Issue by pjunwei95** [CS2103T-W09B2/main#119]
![image](https://user-images.githubusercontent.com/30182679/32362916-8f31f7be-c0a7-11e7-8fe3-e17b5f001b6b.png)

![image](https://user-images.githubusercontent.com/30182679/32362926-993ec372-c0a7-11e7-94ef-4100958c59d7.png)

Giving invalid command format

**Comment by quanle1994** [comment]
Can't run add command from help too. I tried to run the last example in the write-up
![image](https://user-images.githubusercontent.com/17548904/32363383-15a63466-c0aa-11e7-86eb-6efd0f9db197.png)

![image](https://user-images.githubusercontent.com/17548904/32363362-fe880a0c-c0a9-11e7-9a9e-5c9c501fbc7c.png)

**Comment by quanle1994** [comment]
Cannot add task too.
![image](https://user-images.githubusercontent.com/17548904/32363398-29bc95e4-c0aa-11e7-990f-ceccf07ca7e5.png)

**Comment by Esilocke** [comment]
@quanle1994 
![image](https://user-images.githubusercontent.com/26959239/32363874-6dd72986-c0ac-11e7-82e5-9ccc014c9612.png)

You'll need to add the prefixes even with incomplete data, but yes, removing the need for the prefixes would be good. Thanks!

**Comment by jeffreygohkw** [comment]
User Guide has been updated to address this issue #134
