### ISSUE TITLE
Unknown Commands

### ISSUE THREAD

**Issue by pjunwei95** [CS2103T-W09B2/main#124]
![image](https://user-images.githubusercontent.com/30182679/32363746-bd576918-c0ab-11e7-8a70-a726e8ef6675.png)
I assume that this is to be updated later? export and autocomplete isn't working

**Comment by jeffreygohkw** [comment]
Yes, these are our plans for the future and are not in the V1.4 release.

**Comment by jeffreygohkw** [comment]
User Guide has been updated to address this issue #134
