### ISSUE TITLE
Everything on track?

### ISSUE THREAD

**Issue by damithc** [CS2103T-W09B2/main#154]
Everything on track to submit tomorrow? Remember to read submission instructions carefully and plan to finish submissions at least few hours before the deadline. All the best 👍

**Comment by Esilocke** [comment]
We are polishing up and fixing some minor bugs that we found. We'll take note of the instructions!

**Comment by charlesgohck** [comment]
Everything submitted
@Esilocke @wangyiming1019 @jeffreygohkw 
**Great job guys 👍 **
