### ISSUE TITLE
Update developer guide

### ISSUE THREAD

**Issue by Esilocke** [CS2103T-W09B2/main#44]
Update developer guide to describe how features are implemented.
Things to consider: 
* How the feature is implemented.
* Why it is implemented that way.
* Alternatives considered.

**Comment by Esilocke** [comment]
#41 
PR for Tasks documentation

**Comment by jeffreygohkw** [comment]
#43, #62  
PR for Privacy documentation

**Comment by wangyiming1019** [comment]
#58 
PR for Add/Delete Tag documentation

**Comment by charlesgohck** [comment]
https://github.com/CS2103AUG2017-W09-B2/main/pull/31
PR for Sort documentation
